### ISSUE TITLE
Sharin link not working

### ISSUE THREAD

**Issue by ioana-chiorean** [LeoMcA/thanks.mozilla.community#1]
1. Give a thank you 
2. Copy/paste the link and open it 

=> Server not found

**Comment by sayak-sarkar** [comment]
Just checked out the issue. It's because the link generated points to http://share.mozilla.community, which is not a valid domain yet, while the application is currently hosted on a temporary domain. 

@LeoMcA I think we can close this issue, however, do you think we should make the domain soft coded instead of being hard coded to prevent hassles during deployment?

**Comment by ioana-chiorean** [comment]
This is not under development anymore. 😢
Will reopen if this will restart! 🍀 ✌🏽
